services:
  server:
    build:
      context: .
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/perai
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: postgres
    user: postgres
    environment:
      - POSTGRES_DB=perai
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5